# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'PopDemo' do

pod ‘pop’

  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PopDemo

  target 'PopDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PopDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
